export {
  isHealthKitAvailable,
  requestPermissions,
  syncWellness,
  syncWorkouts,
  fullSync,
  getAppleHealthConnection,
  saveAppleHealthConnection,
  disconnectAppleHealth,
  updateLastSyncedAt,
  mockAppleHealthData,
  calculateAppleReadiness,
  fillSampleData,
} from './appleHealth';

export {
  runFullCoachingPipeline,
  generateCoachingPlan,
  analyzeCompletedRun,
  getOptimizedSession,
  runWeeklyAdaptation,
  getAthleteState,
  getLatestBottleneck,
  getActivePhilosophy,
  getBottleneckHistory,
  getLatestAdaptation,
  getAdaptationHistory,
  getTodayDecision,
  saveDailyChoice,
  getCoachingSummary,
} from './coachingEngine';
